name: coqui
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.0=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py39h7196dd7_0
  - gnutls=3.6.13=h85f3911_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=13.0.85=hf384b4a_0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.2=he9a06e4_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py39h9399b63_1
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.5.4=h26f9b46_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=8_cp39
  - pytorch=2.5.1=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h9399b63_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.5.1=py39_cu124
  - torchtriton=3.1.0=py39
  - torchvision=0.20.1=py39_cu124
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.0.1
      - babel==2.17.0
      - blis==0.7.11
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.0
      - coqpit-config==0.1.1
      - coqui-tts==0.25.3
      - coqui-tts-trainer==0.2.0
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.1.6
      - dateparser==1.1.8
      - decorator==5.2.1
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - gruut==2.4.0
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - joblib==1.5.2
      - jsonlines==1.2.0
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - marisa-trie==1.3.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - monotonic-alignment-search==0.2.0
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - murmurhash==1.0.13
      - num2words==0.5.14
      - numba==0.60.0
      - numpy==1.26.4
      - packaging==25.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - preshed==3.0.10
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.10.23
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.4.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sudachidict-core==20250825
      - sudachipy==0.6.10
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - transformers==4.46.2
      - typeguard==4.4.4
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==2.0.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/oscar/miniconda3/envs/coqui
